# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '11.0'

target 'C:\Users\osian\Desktop\codecanyon-19128672-ionic-2-app-for-woocommerce\cc106appdev-master\platforms\ios\SolucionesCR' do
	project 'C:\Users\osian\Desktop\codecanyon-19128672-ionic-2-app-for-woocommerce\cc106appdev-master\platforms\ios\SolucionesCR.xcodeproj'
	pod 'OneSignal', '2.13.1'
end
